"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from grpc import aio as _aio
import PrintingControl_pb2 as _PrintingControl_pb2
import SiLAFramework_pb2 as _SiLAFramework_pb2
import abc as _abc_1
import grpc as _grpc
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class SiLAPrintingControlStub:
    """Provides a set of commands for controlling the printer"""

    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> SiLAPrintingControlAsyncStub: ...
    Print: _grpc.UnaryUnaryMultiCallable[_PrintingControl_pb2.Print_Parameters, _SiLAFramework_pb2.CommandConfirmation]
    """Prints a document. Upload the file with the SiLA Binary Upload feature first, then pass its binaryTransferUUID here."""
    Print_Info: _grpc.UnaryStreamMultiCallable[_SiLAFramework_pb2.CommandExecutionUUID, _SiLAFramework_pb2.ExecutionInfo]
    """Monitor the state of Print"""
    Print_Result: _grpc.UnaryUnaryMultiCallable[_SiLAFramework_pb2.CommandExecutionUUID, _PrintingControl_pb2.Print_Responses]
    """Retrieve result of Print"""
    ScanPage: _grpc.UnaryUnaryMultiCallable[_PrintingControl_pb2.ScanPage_Parameters, _SiLAFramework_pb2.CommandConfirmation]
    """Scans a page from the document feeder."""
    ScanPage_Info: _grpc.UnaryStreamMultiCallable[_SiLAFramework_pb2.CommandExecutionUUID, _SiLAFramework_pb2.ExecutionInfo]
    """Monitor the state of ScanPage"""
    ScanPage_Result: _grpc.UnaryUnaryMultiCallable[_SiLAFramework_pb2.CommandExecutionUUID, _PrintingControl_pb2.ScanPage_Responses]
    """Retrieve result of ScanPage"""
    FlushScan: _grpc.UnaryUnaryMultiCallable[_PrintingControl_pb2.FlushScan_Parameters, _SiLAFramework_pb2.CommandConfirmation]
    """Flushes the scan buffer."""
    FlushScan_Info: _grpc.UnaryStreamMultiCallable[_SiLAFramework_pb2.CommandExecutionUUID, _SiLAFramework_pb2.ExecutionInfo]
    """Monitor the state of FlushScan"""
    FlushScan_Result: _grpc.UnaryUnaryMultiCallable[_SiLAFramework_pb2.CommandExecutionUUID, _PrintingControl_pb2.FlushScan_Responses]
    """Retrieve result of FlushScan"""
    Subscribe_CurrentPrinterStatus: _grpc.UnaryStreamMultiCallable[_PrintingControl_pb2.Subscribe_CurrentPrinterStatus_Parameters, _PrintingControl_pb2.Subscribe_CurrentPrinterStatus_Responses]
    """The current status of the printer."""

@_typing.type_check_only
class SiLAPrintingControlAsyncStub(SiLAPrintingControlStub):
    """Provides a set of commands for controlling the printer"""

    def __init__(self, channel: _aio.Channel) -> None: ...
    Print: _aio.UnaryUnaryMultiCallable[_PrintingControl_pb2.Print_Parameters, _SiLAFramework_pb2.CommandConfirmation]  # type: ignore[assignment]
    """Prints a document. Upload the file with the SiLA Binary Upload feature first, then pass its binaryTransferUUID here."""
    Print_Info: _aio.UnaryStreamMultiCallable[_SiLAFramework_pb2.CommandExecutionUUID, _SiLAFramework_pb2.ExecutionInfo]  # type: ignore[assignment]
    """Monitor the state of Print"""
    Print_Result: _aio.UnaryUnaryMultiCallable[_SiLAFramework_pb2.CommandExecutionUUID, _PrintingControl_pb2.Print_Responses]  # type: ignore[assignment]
    """Retrieve result of Print"""
    ScanPage: _aio.UnaryUnaryMultiCallable[_PrintingControl_pb2.ScanPage_Parameters, _SiLAFramework_pb2.CommandConfirmation]  # type: ignore[assignment]
    """Scans a page from the document feeder."""
    ScanPage_Info: _aio.UnaryStreamMultiCallable[_SiLAFramework_pb2.CommandExecutionUUID, _SiLAFramework_pb2.ExecutionInfo]  # type: ignore[assignment]
    """Monitor the state of ScanPage"""
    ScanPage_Result: _aio.UnaryUnaryMultiCallable[_SiLAFramework_pb2.CommandExecutionUUID, _PrintingControl_pb2.ScanPage_Responses]  # type: ignore[assignment]
    """Retrieve result of ScanPage"""
    FlushScan: _aio.UnaryUnaryMultiCallable[_PrintingControl_pb2.FlushScan_Parameters, _SiLAFramework_pb2.CommandConfirmation]  # type: ignore[assignment]
    """Flushes the scan buffer."""
    FlushScan_Info: _aio.UnaryStreamMultiCallable[_SiLAFramework_pb2.CommandExecutionUUID, _SiLAFramework_pb2.ExecutionInfo]  # type: ignore[assignment]
    """Monitor the state of FlushScan"""
    FlushScan_Result: _aio.UnaryUnaryMultiCallable[_SiLAFramework_pb2.CommandExecutionUUID, _PrintingControl_pb2.FlushScan_Responses]  # type: ignore[assignment]
    """Retrieve result of FlushScan"""
    Subscribe_CurrentPrinterStatus: _aio.UnaryStreamMultiCallable[_PrintingControl_pb2.Subscribe_CurrentPrinterStatus_Parameters, _PrintingControl_pb2.Subscribe_CurrentPrinterStatus_Responses]  # type: ignore[assignment]
    """The current status of the printer."""

class SiLAPrintingControlServicer(metaclass=_abc_1.ABCMeta):
    """Provides a set of commands for controlling the printer"""

    @_abc_1.abstractmethod
    def Print(
        self,
        request: _PrintingControl_pb2.Print_Parameters,
        context: _ServicerContext,
    ) -> _typing.Union[_SiLAFramework_pb2.CommandConfirmation, _abc.Awaitable[_SiLAFramework_pb2.CommandConfirmation]]:
        """Prints a document. Upload the file with the SiLA Binary Upload feature first, then pass its binaryTransferUUID here."""

    @_abc_1.abstractmethod
    def Print_Info(
        self,
        request: _SiLAFramework_pb2.CommandExecutionUUID,
        context: _ServicerContext,
    ) -> _typing.Union[_abc.Iterator[_SiLAFramework_pb2.ExecutionInfo], _abc.AsyncIterator[_SiLAFramework_pb2.ExecutionInfo]]:
        """Monitor the state of Print"""

    @_abc_1.abstractmethod
    def Print_Result(
        self,
        request: _SiLAFramework_pb2.CommandExecutionUUID,
        context: _ServicerContext,
    ) -> _typing.Union[_PrintingControl_pb2.Print_Responses, _abc.Awaitable[_PrintingControl_pb2.Print_Responses]]:
        """Retrieve result of Print"""

    @_abc_1.abstractmethod
    def ScanPage(
        self,
        request: _PrintingControl_pb2.ScanPage_Parameters,
        context: _ServicerContext,
    ) -> _typing.Union[_SiLAFramework_pb2.CommandConfirmation, _abc.Awaitable[_SiLAFramework_pb2.CommandConfirmation]]:
        """Scans a page from the document feeder."""

    @_abc_1.abstractmethod
    def ScanPage_Info(
        self,
        request: _SiLAFramework_pb2.CommandExecutionUUID,
        context: _ServicerContext,
    ) -> _typing.Union[_abc.Iterator[_SiLAFramework_pb2.ExecutionInfo], _abc.AsyncIterator[_SiLAFramework_pb2.ExecutionInfo]]:
        """Monitor the state of ScanPage"""

    @_abc_1.abstractmethod
    def ScanPage_Result(
        self,
        request: _SiLAFramework_pb2.CommandExecutionUUID,
        context: _ServicerContext,
    ) -> _typing.Union[_PrintingControl_pb2.ScanPage_Responses, _abc.Awaitable[_PrintingControl_pb2.ScanPage_Responses]]:
        """Retrieve result of ScanPage"""

    @_abc_1.abstractmethod
    def FlushScan(
        self,
        request: _PrintingControl_pb2.FlushScan_Parameters,
        context: _ServicerContext,
    ) -> _typing.Union[_SiLAFramework_pb2.CommandConfirmation, _abc.Awaitable[_SiLAFramework_pb2.CommandConfirmation]]:
        """Flushes the scan buffer."""

    @_abc_1.abstractmethod
    def FlushScan_Info(
        self,
        request: _SiLAFramework_pb2.CommandExecutionUUID,
        context: _ServicerContext,
    ) -> _typing.Union[_abc.Iterator[_SiLAFramework_pb2.ExecutionInfo], _abc.AsyncIterator[_SiLAFramework_pb2.ExecutionInfo]]:
        """Monitor the state of FlushScan"""

    @_abc_1.abstractmethod
    def FlushScan_Result(
        self,
        request: _SiLAFramework_pb2.CommandExecutionUUID,
        context: _ServicerContext,
    ) -> _typing.Union[_PrintingControl_pb2.FlushScan_Responses, _abc.Awaitable[_PrintingControl_pb2.FlushScan_Responses]]:
        """Retrieve result of FlushScan"""

    @_abc_1.abstractmethod
    def Subscribe_CurrentPrinterStatus(
        self,
        request: _PrintingControl_pb2.Subscribe_CurrentPrinterStatus_Parameters,
        context: _ServicerContext,
    ) -> _typing.Union[_abc.Iterator[_PrintingControl_pb2.Subscribe_CurrentPrinterStatus_Responses], _abc.AsyncIterator[_PrintingControl_pb2.Subscribe_CurrentPrinterStatus_Responses]]:
        """The current status of the printer."""

def add_SiLAPrintingControlServicer_to_server(servicer: SiLAPrintingControlServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...
