"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
import SiLAFramework_pb2 as _SiLAFramework_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class Print_Parameters(_message.Message):
    """Parameters for Print"""

    DESCRIPTOR: _descriptor.Descriptor

    FILE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def File(self) -> _SiLAFramework_pb2.String:
        """The binaryTransferUUID of the file uploaded with the SiLA Binary Upload feature."""

    def __init__(
        self,
        *,
        File: _SiLAFramework_pb2.String | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["File", b"File"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["File", b"File"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Print_Parameters: _TypeAlias = Print_Parameters  # noqa: Y015

@_typing.final
class Print_Responses(_message.Message):
    """Responses of Print"""

    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class PrintResult_Struct(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        PRINTSTATUS_FIELD_NUMBER: _builtins.int
        PRINTMESSAGE_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def PrintStatus(self) -> _SiLAFramework_pb2.Integer:
            """Status of the print operation."""

        @_builtins.property
        def PrintMessage(self) -> _SiLAFramework_pb2.String:
            """Message related to the print operation."""

        def __init__(
            self,
            *,
            PrintStatus: _SiLAFramework_pb2.Integer | None = ...,
            PrintMessage: _SiLAFramework_pb2.String | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["PrintMessage", b"PrintMessage", "PrintStatus", b"PrintStatus"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["PrintMessage", b"PrintMessage", "PrintStatus", b"PrintStatus"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    PRINTRESULT_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def PrintResult(self) -> Global___Print_Responses.PrintResult_Struct:
        """Result of the print operation."""

    def __init__(
        self,
        *,
        PrintResult: Global___Print_Responses.PrintResult_Struct | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["PrintResult", b"PrintResult"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["PrintResult", b"PrintResult"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Print_Responses: _TypeAlias = Print_Responses  # noqa: Y015

@_typing.final
class ScanPage_Parameters(_message.Message):
    """Parameters for ScanPage"""

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ScanPage_Parameters: _TypeAlias = ScanPage_Parameters  # noqa: Y015

@_typing.final
class ScanPage_Responses(_message.Message):
    """Responses of ScanPage"""

    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class ScanResult_Struct(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        SCANSTATUS_FIELD_NUMBER: _builtins.int
        SCANMESSAGE_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def ScanStatus(self) -> _SiLAFramework_pb2.Integer:
            """Status of the scan operation."""

        @_builtins.property
        def ScanMessage(self) -> _SiLAFramework_pb2.String:
            """Message related to the scan operation."""

        def __init__(
            self,
            *,
            ScanStatus: _SiLAFramework_pb2.Integer | None = ...,
            ScanMessage: _SiLAFramework_pb2.String | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["ScanMessage", b"ScanMessage", "ScanStatus", b"ScanStatus"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["ScanMessage", b"ScanMessage", "ScanStatus", b"ScanStatus"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    SCANRESULT_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def ScanResult(self) -> Global___ScanPage_Responses.ScanResult_Struct:
        """Result of the scan operation."""

    def __init__(
        self,
        *,
        ScanResult: Global___ScanPage_Responses.ScanResult_Struct | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["ScanResult", b"ScanResult"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["ScanResult", b"ScanResult"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ScanPage_Responses: _TypeAlias = ScanPage_Responses  # noqa: Y015

@_typing.final
class FlushScan_Parameters(_message.Message):
    """Parameters for FlushScan"""

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___FlushScan_Parameters: _TypeAlias = FlushScan_Parameters  # noqa: Y015

@_typing.final
class FlushScan_Responses(_message.Message):
    """Responses of FlushScan"""

    DESCRIPTOR: _descriptor.Descriptor

    SCANNINGSTATUS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def ScanningStatus(self) -> _SiLAFramework_pb2.Integer:
        """Status of the scanning operation."""

    def __init__(
        self,
        *,
        ScanningStatus: _SiLAFramework_pb2.Integer | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["ScanningStatus", b"ScanningStatus"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["ScanningStatus", b"ScanningStatus"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___FlushScan_Responses: _TypeAlias = FlushScan_Responses  # noqa: Y015

@_typing.final
class Subscribe_CurrentPrinterStatus_Parameters(_message.Message):
    """Parameters for CurrentPrinterStatus"""

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Subscribe_CurrentPrinterStatus_Parameters: _TypeAlias = Subscribe_CurrentPrinterStatus_Parameters  # noqa: Y015

@_typing.final
class Subscribe_CurrentPrinterStatus_Responses(_message.Message):
    """Responses of CurrentPrinterStatus"""

    DESCRIPTOR: _descriptor.Descriptor

    CURRENTPRINTERSTATUS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def CurrentPrinterStatus(self) -> _SiLAFramework_pb2.String:
        """The current status of the printer."""

    def __init__(
        self,
        *,
        CurrentPrinterStatus: _SiLAFramework_pb2.String | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["CurrentPrinterStatus", b"CurrentPrinterStatus"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["CurrentPrinterStatus", b"CurrentPrinterStatus"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Subscribe_CurrentPrinterStatus_Responses: _TypeAlias = Subscribe_CurrentPrinterStatus_Responses  # noqa: Y015
