# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import PrintingControl_pb2 as PrintingControl__pb2
import SiLAFramework_pb2 as SiLAFramework__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in PrintingControl_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SiLAPrintingControlStub:
    """Provides a set of commands for controlling the printer 
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Print = channel.unary_unary(
                '/sila2.org.silastandard.printer.silaprintingcontrol.v1.SiLAPrintingControl/Print',
                request_serializer=PrintingControl__pb2.Print_Parameters.SerializeToString,
                response_deserializer=SiLAFramework__pb2.CommandConfirmation.FromString,
                _registered_method=True)
        self.Print_Info = channel.unary_stream(
                '/sila2.org.silastandard.printer.silaprintingcontrol.v1.SiLAPrintingControl/Print_Info',
                request_serializer=SiLAFramework__pb2.CommandExecutionUUID.SerializeToString,
                response_deserializer=SiLAFramework__pb2.ExecutionInfo.FromString,
                _registered_method=True)
        self.Print_Result = channel.unary_unary(
                '/sila2.org.silastandard.printer.silaprintingcontrol.v1.SiLAPrintingControl/Print_Result',
                request_serializer=SiLAFramework__pb2.CommandExecutionUUID.SerializeToString,
                response_deserializer=PrintingControl__pb2.Print_Responses.FromString,
                _registered_method=True)
        self.ScanPage = channel.unary_unary(
                '/sila2.org.silastandard.printer.silaprintingcontrol.v1.SiLAPrintingControl/ScanPage',
                request_serializer=PrintingControl__pb2.ScanPage_Parameters.SerializeToString,
                response_deserializer=SiLAFramework__pb2.CommandConfirmation.FromString,
                _registered_method=True)
        self.ScanPage_Info = channel.unary_stream(
                '/sila2.org.silastandard.printer.silaprintingcontrol.v1.SiLAPrintingControl/ScanPage_Info',
                request_serializer=SiLAFramework__pb2.CommandExecutionUUID.SerializeToString,
                response_deserializer=SiLAFramework__pb2.ExecutionInfo.FromString,
                _registered_method=True)
        self.ScanPage_Result = channel.unary_unary(
                '/sila2.org.silastandard.printer.silaprintingcontrol.v1.SiLAPrintingControl/ScanPage_Result',
                request_serializer=SiLAFramework__pb2.CommandExecutionUUID.SerializeToString,
                response_deserializer=PrintingControl__pb2.ScanPage_Responses.FromString,
                _registered_method=True)
        self.FlushScan = channel.unary_unary(
                '/sila2.org.silastandard.printer.silaprintingcontrol.v1.SiLAPrintingControl/FlushScan',
                request_serializer=PrintingControl__pb2.FlushScan_Parameters.SerializeToString,
                response_deserializer=SiLAFramework__pb2.CommandConfirmation.FromString,
                _registered_method=True)
        self.FlushScan_Info = channel.unary_stream(
                '/sila2.org.silastandard.printer.silaprintingcontrol.v1.SiLAPrintingControl/FlushScan_Info',
                request_serializer=SiLAFramework__pb2.CommandExecutionUUID.SerializeToString,
                response_deserializer=SiLAFramework__pb2.ExecutionInfo.FromString,
                _registered_method=True)
        self.FlushScan_Result = channel.unary_unary(
                '/sila2.org.silastandard.printer.silaprintingcontrol.v1.SiLAPrintingControl/FlushScan_Result',
                request_serializer=SiLAFramework__pb2.CommandExecutionUUID.SerializeToString,
                response_deserializer=PrintingControl__pb2.FlushScan_Responses.FromString,
                _registered_method=True)
        self.Subscribe_CurrentPrinterStatus = channel.unary_stream(
                '/sila2.org.silastandard.printer.silaprintingcontrol.v1.SiLAPrintingControl/Subscribe_CurrentPrinterStatus',
                request_serializer=PrintingControl__pb2.Subscribe_CurrentPrinterStatus_Parameters.SerializeToString,
                response_deserializer=PrintingControl__pb2.Subscribe_CurrentPrinterStatus_Responses.FromString,
                _registered_method=True)


class SiLAPrintingControlServicer:
    """Provides a set of commands for controlling the printer 
    """

    def Print(self, request, context):
        """Prints a document. Upload the file with the SiLA Binary Upload feature first, then pass its binaryTransferUUID here. 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Print_Info(self, request, context):
        """Monitor the state of Print 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Print_Result(self, request, context):
        """Retrieve result of Print 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ScanPage(self, request, context):
        """Scans a page from the document feeder. 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ScanPage_Info(self, request, context):
        """Monitor the state of ScanPage 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ScanPage_Result(self, request, context):
        """Retrieve result of ScanPage 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FlushScan(self, request, context):
        """Flushes the scan buffer. 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FlushScan_Info(self, request, context):
        """Monitor the state of FlushScan 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FlushScan_Result(self, request, context):
        """Retrieve result of FlushScan 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Subscribe_CurrentPrinterStatus(self, request, context):
        """The current status of the printer. 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SiLAPrintingControlServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Print': grpc.unary_unary_rpc_method_handler(
                    servicer.Print,
                    request_deserializer=PrintingControl__pb2.Print_Parameters.FromString,
                    response_serializer=SiLAFramework__pb2.CommandConfirmation.SerializeToString,
            ),
            'Print_Info': grpc.unary_stream_rpc_method_handler(
                    servicer.Print_Info,
                    request_deserializer=SiLAFramework__pb2.CommandExecutionUUID.FromString,
                    response_serializer=SiLAFramework__pb2.ExecutionInfo.SerializeToString,
            ),
            'Print_Result': grpc.unary_unary_rpc_method_handler(
                    servicer.Print_Result,
                    request_deserializer=SiLAFramework__pb2.CommandExecutionUUID.FromString,
                    response_serializer=PrintingControl__pb2.Print_Responses.SerializeToString,
            ),
            'ScanPage': grpc.unary_unary_rpc_method_handler(
                    servicer.ScanPage,
                    request_deserializer=PrintingControl__pb2.ScanPage_Parameters.FromString,
                    response_serializer=SiLAFramework__pb2.CommandConfirmation.SerializeToString,
            ),
            'ScanPage_Info': grpc.unary_stream_rpc_method_handler(
                    servicer.ScanPage_Info,
                    request_deserializer=SiLAFramework__pb2.CommandExecutionUUID.FromString,
                    response_serializer=SiLAFramework__pb2.ExecutionInfo.SerializeToString,
            ),
            'ScanPage_Result': grpc.unary_unary_rpc_method_handler(
                    servicer.ScanPage_Result,
                    request_deserializer=SiLAFramework__pb2.CommandExecutionUUID.FromString,
                    response_serializer=PrintingControl__pb2.ScanPage_Responses.SerializeToString,
            ),
            'FlushScan': grpc.unary_unary_rpc_method_handler(
                    servicer.FlushScan,
                    request_deserializer=PrintingControl__pb2.FlushScan_Parameters.FromString,
                    response_serializer=SiLAFramework__pb2.CommandConfirmation.SerializeToString,
            ),
            'FlushScan_Info': grpc.unary_stream_rpc_method_handler(
                    servicer.FlushScan_Info,
                    request_deserializer=SiLAFramework__pb2.CommandExecutionUUID.FromString,
                    response_serializer=SiLAFramework__pb2.ExecutionInfo.SerializeToString,
            ),
            'FlushScan_Result': grpc.unary_unary_rpc_method_handler(
                    servicer.FlushScan_Result,
                    request_deserializer=SiLAFramework__pb2.CommandExecutionUUID.FromString,
                    response_serializer=PrintingControl__pb2.FlushScan_Responses.SerializeToString,
            ),
            'Subscribe_CurrentPrinterStatus': grpc.unary_stream_rpc_method_handler(
                    servicer.Subscribe_CurrentPrinterStatus,
                    request_deserializer=PrintingControl__pb2.Subscribe_CurrentPrinterStatus_Parameters.FromString,
                    response_serializer=PrintingControl__pb2.Subscribe_CurrentPrinterStatus_Responses.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sila2.org.silastandard.printer.silaprintingcontrol.v1.SiLAPrintingControl', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sila2.org.silastandard.printer.silaprintingcontrol.v1.SiLAPrintingControl', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SiLAPrintingControl:
    """Provides a set of commands for controlling the printer 
    """

    @staticmethod
    def Print(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sila2.org.silastandard.printer.silaprintingcontrol.v1.SiLAPrintingControl/Print',
            PrintingControl__pb2.Print_Parameters.SerializeToString,
            SiLAFramework__pb2.CommandConfirmation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Print_Info(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/sila2.org.silastandard.printer.silaprintingcontrol.v1.SiLAPrintingControl/Print_Info',
            SiLAFramework__pb2.CommandExecutionUUID.SerializeToString,
            SiLAFramework__pb2.ExecutionInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Print_Result(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sila2.org.silastandard.printer.silaprintingcontrol.v1.SiLAPrintingControl/Print_Result',
            SiLAFramework__pb2.CommandExecutionUUID.SerializeToString,
            PrintingControl__pb2.Print_Responses.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ScanPage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sila2.org.silastandard.printer.silaprintingcontrol.v1.SiLAPrintingControl/ScanPage',
            PrintingControl__pb2.ScanPage_Parameters.SerializeToString,
            SiLAFramework__pb2.CommandConfirmation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ScanPage_Info(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/sila2.org.silastandard.printer.silaprintingcontrol.v1.SiLAPrintingControl/ScanPage_Info',
            SiLAFramework__pb2.CommandExecutionUUID.SerializeToString,
            SiLAFramework__pb2.ExecutionInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ScanPage_Result(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sila2.org.silastandard.printer.silaprintingcontrol.v1.SiLAPrintingControl/ScanPage_Result',
            SiLAFramework__pb2.CommandExecutionUUID.SerializeToString,
            PrintingControl__pb2.ScanPage_Responses.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FlushScan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sila2.org.silastandard.printer.silaprintingcontrol.v1.SiLAPrintingControl/FlushScan',
            PrintingControl__pb2.FlushScan_Parameters.SerializeToString,
            SiLAFramework__pb2.CommandConfirmation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FlushScan_Info(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/sila2.org.silastandard.printer.silaprintingcontrol.v1.SiLAPrintingControl/FlushScan_Info',
            SiLAFramework__pb2.CommandExecutionUUID.SerializeToString,
            SiLAFramework__pb2.ExecutionInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FlushScan_Result(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sila2.org.silastandard.printer.silaprintingcontrol.v1.SiLAPrintingControl/FlushScan_Result',
            SiLAFramework__pb2.CommandExecutionUUID.SerializeToString,
            PrintingControl__pb2.FlushScan_Responses.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Subscribe_CurrentPrinterStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/sila2.org.silastandard.printer.silaprintingcontrol.v1.SiLAPrintingControl/Subscribe_CurrentPrinterStatus',
            PrintingControl__pb2.Subscribe_CurrentPrinterStatus_Parameters.SerializeToString,
            PrintingControl__pb2.Subscribe_CurrentPrinterStatus_Responses.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
