"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import SiLAFramework_pb2 as _SiLAFramework_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class CreateBinaryRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    BINARYSIZE_FIELD_NUMBER: _builtins.int
    CHUNKCOUNT_FIELD_NUMBER: _builtins.int
    PARAMETERIDENTIFIER_FIELD_NUMBER: _builtins.int
    binarySize: _builtins.int
    chunkCount: _builtins.int
    parameterIdentifier: _builtins.str
    """fully qualified parameter identifier"""
    def __init__(
        self,
        *,
        binarySize: _builtins.int = ...,
        chunkCount: _builtins.int = ...,
        parameterIdentifier: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["binarySize", b"binarySize", "chunkCount", b"chunkCount", "parameterIdentifier", b"parameterIdentifier"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CreateBinaryRequest: _TypeAlias = CreateBinaryRequest  # noqa: Y015

@_typing.final
class CreateBinaryResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    BINARYTRANSFERUUID_FIELD_NUMBER: _builtins.int
    LIFETIMEOFBINARY_FIELD_NUMBER: _builtins.int
    binaryTransferUUID: _builtins.str
    @_builtins.property
    def lifetimeOfBinary(self) -> _SiLAFramework_pb2.Duration: ...
    def __init__(
        self,
        *,
        binaryTransferUUID: _builtins.str = ...,
        lifetimeOfBinary: _SiLAFramework_pb2.Duration | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["lifetimeOfBinary", b"lifetimeOfBinary"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["binaryTransferUUID", b"binaryTransferUUID", "lifetimeOfBinary", b"lifetimeOfBinary"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CreateBinaryResponse: _TypeAlias = CreateBinaryResponse  # noqa: Y015

@_typing.final
class UploadChunkRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    BINARYTRANSFERUUID_FIELD_NUMBER: _builtins.int
    CHUNKINDEX_FIELD_NUMBER: _builtins.int
    PAYLOAD_FIELD_NUMBER: _builtins.int
    binaryTransferUUID: _builtins.str
    chunkIndex: _builtins.int
    payload: _builtins.bytes
    def __init__(
        self,
        *,
        binaryTransferUUID: _builtins.str = ...,
        chunkIndex: _builtins.int = ...,
        payload: _builtins.bytes = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["binaryTransferUUID", b"binaryTransferUUID", "chunkIndex", b"chunkIndex", "payload", b"payload"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___UploadChunkRequest: _TypeAlias = UploadChunkRequest  # noqa: Y015

@_typing.final
class UploadChunkResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    BINARYTRANSFERUUID_FIELD_NUMBER: _builtins.int
    CHUNKINDEX_FIELD_NUMBER: _builtins.int
    LIFETIMEOFBINARY_FIELD_NUMBER: _builtins.int
    binaryTransferUUID: _builtins.str
    chunkIndex: _builtins.int
    @_builtins.property
    def lifetimeOfBinary(self) -> _SiLAFramework_pb2.Duration: ...
    def __init__(
        self,
        *,
        binaryTransferUUID: _builtins.str = ...,
        chunkIndex: _builtins.int = ...,
        lifetimeOfBinary: _SiLAFramework_pb2.Duration | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["lifetimeOfBinary", b"lifetimeOfBinary"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["binaryTransferUUID", b"binaryTransferUUID", "chunkIndex", b"chunkIndex", "lifetimeOfBinary", b"lifetimeOfBinary"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___UploadChunkResponse: _TypeAlias = UploadChunkResponse  # noqa: Y015

@_typing.final
class DeleteBinaryRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    BINARYTRANSFERUUID_FIELD_NUMBER: _builtins.int
    binaryTransferUUID: _builtins.str
    def __init__(
        self,
        *,
        binaryTransferUUID: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["binaryTransferUUID", b"binaryTransferUUID"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DeleteBinaryRequest: _TypeAlias = DeleteBinaryRequest  # noqa: Y015

@_typing.final
class DeleteBinaryResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DeleteBinaryResponse: _TypeAlias = DeleteBinaryResponse  # noqa: Y015

@_typing.final
class GetBinaryInfoRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    BINARYTRANSFERUUID_FIELD_NUMBER: _builtins.int
    binaryTransferUUID: _builtins.str
    def __init__(
        self,
        *,
        binaryTransferUUID: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["binaryTransferUUID", b"binaryTransferUUID"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetBinaryInfoRequest: _TypeAlias = GetBinaryInfoRequest  # noqa: Y015

@_typing.final
class GetBinaryInfoResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    BINARYSIZE_FIELD_NUMBER: _builtins.int
    LIFETIMEOFBINARY_FIELD_NUMBER: _builtins.int
    binarySize: _builtins.int
    @_builtins.property
    def lifetimeOfBinary(self) -> _SiLAFramework_pb2.Duration: ...
    def __init__(
        self,
        *,
        binarySize: _builtins.int = ...,
        lifetimeOfBinary: _SiLAFramework_pb2.Duration | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["lifetimeOfBinary", b"lifetimeOfBinary"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["binarySize", b"binarySize", "lifetimeOfBinary", b"lifetimeOfBinary"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetBinaryInfoResponse: _TypeAlias = GetBinaryInfoResponse  # noqa: Y015

@_typing.final
class GetChunkRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    BINARYTRANSFERUUID_FIELD_NUMBER: _builtins.int
    OFFSET_FIELD_NUMBER: _builtins.int
    LENGTH_FIELD_NUMBER: _builtins.int
    binaryTransferUUID: _builtins.str
    offset: _builtins.int
    length: _builtins.int
    def __init__(
        self,
        *,
        binaryTransferUUID: _builtins.str = ...,
        offset: _builtins.int = ...,
        length: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["binaryTransferUUID", b"binaryTransferUUID", "length", b"length", "offset", b"offset"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetChunkRequest: _TypeAlias = GetChunkRequest  # noqa: Y015

@_typing.final
class GetChunkResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    BINARYTRANSFERUUID_FIELD_NUMBER: _builtins.int
    OFFSET_FIELD_NUMBER: _builtins.int
    PAYLOAD_FIELD_NUMBER: _builtins.int
    LIFETIMEOFBINARY_FIELD_NUMBER: _builtins.int
    binaryTransferUUID: _builtins.str
    offset: _builtins.int
    payload: _builtins.bytes
    @_builtins.property
    def lifetimeOfBinary(self) -> _SiLAFramework_pb2.Duration: ...
    def __init__(
        self,
        *,
        binaryTransferUUID: _builtins.str = ...,
        offset: _builtins.int = ...,
        payload: _builtins.bytes = ...,
        lifetimeOfBinary: _SiLAFramework_pb2.Duration | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["lifetimeOfBinary", b"lifetimeOfBinary"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["binaryTransferUUID", b"binaryTransferUUID", "lifetimeOfBinary", b"lifetimeOfBinary", "offset", b"offset", "payload", b"payload"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetChunkResponse: _TypeAlias = GetChunkResponse  # noqa: Y015

@_typing.final
class BinaryTransferError(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _ErrorType:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _ErrorTypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[BinaryTransferError._ErrorType.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        INVALID_BINARY_TRANSFER_UUID: BinaryTransferError._ErrorType.ValueType  # 0
        BINARY_UPLOAD_FAILED: BinaryTransferError._ErrorType.ValueType  # 1
        BINARY_DOWNLOAD_FAILED: BinaryTransferError._ErrorType.ValueType  # 2

    class ErrorType(_ErrorType, metaclass=_ErrorTypeEnumTypeWrapper): ...
    INVALID_BINARY_TRANSFER_UUID: BinaryTransferError.ErrorType.ValueType  # 0
    BINARY_UPLOAD_FAILED: BinaryTransferError.ErrorType.ValueType  # 1
    BINARY_DOWNLOAD_FAILED: BinaryTransferError.ErrorType.ValueType  # 2

    ERRORTYPE_FIELD_NUMBER: _builtins.int
    MESSAGE_FIELD_NUMBER: _builtins.int
    errorType: Global___BinaryTransferError.ErrorType.ValueType
    message: _builtins.str
    def __init__(
        self,
        *,
        errorType: Global___BinaryTransferError.ErrorType.ValueType = ...,
        message: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["errorType", b"errorType", "message", b"message"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___BinaryTransferError: _TypeAlias = BinaryTransferError  # noqa: Y015
