"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from grpc import aio as _aio
import SiLABinaryTransfer_pb2 as _SiLABinaryTransfer_pb2
import abc as _abc_1
import grpc as _grpc
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class BinaryUploadStub:
    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> BinaryUploadAsyncStub: ...
    CreateBinary: _grpc.UnaryUnaryMultiCallable[_SiLABinaryTransfer_pb2.CreateBinaryRequest, _SiLABinaryTransfer_pb2.CreateBinaryResponse]
    UploadChunk: _grpc.StreamStreamMultiCallable[_SiLABinaryTransfer_pb2.UploadChunkRequest, _SiLABinaryTransfer_pb2.UploadChunkResponse]
    DeleteBinary: _grpc.UnaryUnaryMultiCallable[_SiLABinaryTransfer_pb2.DeleteBinaryRequest, _SiLABinaryTransfer_pb2.DeleteBinaryResponse]

@_typing.type_check_only
class BinaryUploadAsyncStub(BinaryUploadStub):
    def __init__(self, channel: _aio.Channel) -> None: ...
    CreateBinary: _aio.UnaryUnaryMultiCallable[_SiLABinaryTransfer_pb2.CreateBinaryRequest, _SiLABinaryTransfer_pb2.CreateBinaryResponse]  # type: ignore[assignment]
    UploadChunk: _aio.StreamStreamMultiCallable[_SiLABinaryTransfer_pb2.UploadChunkRequest, _SiLABinaryTransfer_pb2.UploadChunkResponse]  # type: ignore[assignment]
    DeleteBinary: _aio.UnaryUnaryMultiCallable[_SiLABinaryTransfer_pb2.DeleteBinaryRequest, _SiLABinaryTransfer_pb2.DeleteBinaryResponse]  # type: ignore[assignment]

class BinaryUploadServicer(metaclass=_abc_1.ABCMeta):
    @_abc_1.abstractmethod
    def CreateBinary(
        self,
        request: _SiLABinaryTransfer_pb2.CreateBinaryRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_SiLABinaryTransfer_pb2.CreateBinaryResponse, _abc.Awaitable[_SiLABinaryTransfer_pb2.CreateBinaryResponse]]: ...

    @_abc_1.abstractmethod
    def UploadChunk(
        self,
        request_iterator: _MaybeAsyncIterator[_SiLABinaryTransfer_pb2.UploadChunkRequest],
        context: _ServicerContext,
    ) -> _typing.Union[_abc.Iterator[_SiLABinaryTransfer_pb2.UploadChunkResponse], _abc.AsyncIterator[_SiLABinaryTransfer_pb2.UploadChunkResponse]]: ...

    @_abc_1.abstractmethod
    def DeleteBinary(
        self,
        request: _SiLABinaryTransfer_pb2.DeleteBinaryRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_SiLABinaryTransfer_pb2.DeleteBinaryResponse, _abc.Awaitable[_SiLABinaryTransfer_pb2.DeleteBinaryResponse]]: ...

def add_BinaryUploadServicer_to_server(servicer: BinaryUploadServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...

class BinaryDownloadStub:
    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> BinaryDownloadAsyncStub: ...
    GetBinaryInfo: _grpc.UnaryUnaryMultiCallable[_SiLABinaryTransfer_pb2.GetBinaryInfoRequest, _SiLABinaryTransfer_pb2.GetBinaryInfoResponse]
    GetChunk: _grpc.StreamStreamMultiCallable[_SiLABinaryTransfer_pb2.GetChunkRequest, _SiLABinaryTransfer_pb2.GetChunkResponse]
    DeleteBinary: _grpc.UnaryUnaryMultiCallable[_SiLABinaryTransfer_pb2.DeleteBinaryRequest, _SiLABinaryTransfer_pb2.DeleteBinaryResponse]

@_typing.type_check_only
class BinaryDownloadAsyncStub(BinaryDownloadStub):
    def __init__(self, channel: _aio.Channel) -> None: ...
    GetBinaryInfo: _aio.UnaryUnaryMultiCallable[_SiLABinaryTransfer_pb2.GetBinaryInfoRequest, _SiLABinaryTransfer_pb2.GetBinaryInfoResponse]  # type: ignore[assignment]
    GetChunk: _aio.StreamStreamMultiCallable[_SiLABinaryTransfer_pb2.GetChunkRequest, _SiLABinaryTransfer_pb2.GetChunkResponse]  # type: ignore[assignment]
    DeleteBinary: _aio.UnaryUnaryMultiCallable[_SiLABinaryTransfer_pb2.DeleteBinaryRequest, _SiLABinaryTransfer_pb2.DeleteBinaryResponse]  # type: ignore[assignment]

class BinaryDownloadServicer(metaclass=_abc_1.ABCMeta):
    @_abc_1.abstractmethod
    def GetBinaryInfo(
        self,
        request: _SiLABinaryTransfer_pb2.GetBinaryInfoRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_SiLABinaryTransfer_pb2.GetBinaryInfoResponse, _abc.Awaitable[_SiLABinaryTransfer_pb2.GetBinaryInfoResponse]]: ...

    @_abc_1.abstractmethod
    def GetChunk(
        self,
        request_iterator: _MaybeAsyncIterator[_SiLABinaryTransfer_pb2.GetChunkRequest],
        context: _ServicerContext,
    ) -> _typing.Union[_abc.Iterator[_SiLABinaryTransfer_pb2.GetChunkResponse], _abc.AsyncIterator[_SiLABinaryTransfer_pb2.GetChunkResponse]]: ...

    @_abc_1.abstractmethod
    def DeleteBinary(
        self,
        request: _SiLABinaryTransfer_pb2.DeleteBinaryRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_SiLABinaryTransfer_pb2.DeleteBinaryResponse, _abc.Awaitable[_SiLABinaryTransfer_pb2.DeleteBinaryResponse]]: ...

def add_BinaryDownloadServicer_to_server(servicer: BinaryDownloadServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...
