"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class String(_message.Message):
    """-------- SiLA Basic Types --------"""

    DESCRIPTOR: _descriptor.Descriptor

    VALUE_FIELD_NUMBER: _builtins.int
    value: _builtins.str
    def __init__(
        self,
        *,
        value: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___String: _TypeAlias = String  # noqa: Y015

@_typing.final
class Integer(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    VALUE_FIELD_NUMBER: _builtins.int
    value: _builtins.int
    def __init__(
        self,
        *,
        value: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Integer: _TypeAlias = Integer  # noqa: Y015

@_typing.final
class Real(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    VALUE_FIELD_NUMBER: _builtins.int
    value: _builtins.float
    def __init__(
        self,
        *,
        value: _builtins.float = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Real: _TypeAlias = Real  # noqa: Y015

@_typing.final
class Boolean(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    VALUE_FIELD_NUMBER: _builtins.int
    value: _builtins.bool
    def __init__(
        self,
        *,
        value: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Boolean: _TypeAlias = Boolean  # noqa: Y015

@_typing.final
class Binary(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    VALUE_FIELD_NUMBER: _builtins.int
    BINARYTRANSFERUUID_FIELD_NUMBER: _builtins.int
    value: _builtins.bytes
    binaryTransferUUID: _builtins.str
    def __init__(
        self,
        *,
        value: _builtins.bytes = ...,
        binaryTransferUUID: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["binaryTransferUUID", b"binaryTransferUUID", "union", b"union", "value", b"value"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["binaryTransferUUID", b"binaryTransferUUID", "union", b"union", "value", b"value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_union: _TypeAlias = _typing.Literal["value", "binaryTransferUUID"]  # noqa: Y015
    _WhichOneofArgType_union: _TypeAlias = _typing.Literal["union", b"union"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_union) -> _WhichOneofReturnType_union | None: ...

Global___Binary: _TypeAlias = Binary  # noqa: Y015

@_typing.final
class Date(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    DAY_FIELD_NUMBER: _builtins.int
    MONTH_FIELD_NUMBER: _builtins.int
    YEAR_FIELD_NUMBER: _builtins.int
    TIMEZONE_FIELD_NUMBER: _builtins.int
    day: _builtins.int
    month: _builtins.int
    year: _builtins.int
    @_builtins.property
    def timezone(self) -> Global___Timezone: ...
    def __init__(
        self,
        *,
        day: _builtins.int = ...,
        month: _builtins.int = ...,
        year: _builtins.int = ...,
        timezone: Global___Timezone | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["timezone", b"timezone"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["day", b"day", "month", b"month", "timezone", b"timezone", "year", b"year"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Date: _TypeAlias = Date  # noqa: Y015

@_typing.final
class Time(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SECOND_FIELD_NUMBER: _builtins.int
    MINUTE_FIELD_NUMBER: _builtins.int
    HOUR_FIELD_NUMBER: _builtins.int
    TIMEZONE_FIELD_NUMBER: _builtins.int
    MILLISECOND_FIELD_NUMBER: _builtins.int
    second: _builtins.int
    minute: _builtins.int
    hour: _builtins.int
    millisecond: _builtins.int
    @_builtins.property
    def timezone(self) -> Global___Timezone: ...
    def __init__(
        self,
        *,
        second: _builtins.int = ...,
        minute: _builtins.int = ...,
        hour: _builtins.int = ...,
        timezone: Global___Timezone | None = ...,
        millisecond: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["timezone", b"timezone"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["hour", b"hour", "millisecond", b"millisecond", "minute", b"minute", "second", b"second", "timezone", b"timezone"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Time: _TypeAlias = Time  # noqa: Y015

@_typing.final
class Timestamp(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SECOND_FIELD_NUMBER: _builtins.int
    MINUTE_FIELD_NUMBER: _builtins.int
    HOUR_FIELD_NUMBER: _builtins.int
    DAY_FIELD_NUMBER: _builtins.int
    MONTH_FIELD_NUMBER: _builtins.int
    YEAR_FIELD_NUMBER: _builtins.int
    TIMEZONE_FIELD_NUMBER: _builtins.int
    MILLISECOND_FIELD_NUMBER: _builtins.int
    second: _builtins.int
    minute: _builtins.int
    hour: _builtins.int
    day: _builtins.int
    month: _builtins.int
    year: _builtins.int
    millisecond: _builtins.int
    @_builtins.property
    def timezone(self) -> Global___Timezone: ...
    def __init__(
        self,
        *,
        second: _builtins.int = ...,
        minute: _builtins.int = ...,
        hour: _builtins.int = ...,
        day: _builtins.int = ...,
        month: _builtins.int = ...,
        year: _builtins.int = ...,
        timezone: Global___Timezone | None = ...,
        millisecond: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["timezone", b"timezone"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["day", b"day", "hour", b"hour", "millisecond", b"millisecond", "minute", b"minute", "month", b"month", "second", b"second", "timezone", b"timezone", "year", b"year"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Timestamp: _TypeAlias = Timestamp  # noqa: Y015

@_typing.final
class Any(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TYPE_FIELD_NUMBER: _builtins.int
    PAYLOAD_FIELD_NUMBER: _builtins.int
    type: _builtins.str
    payload: _builtins.bytes
    def __init__(
        self,
        *,
        type: _builtins.str = ...,
        payload: _builtins.bytes = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["payload", b"payload", "type", b"type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Any: _TypeAlias = Any  # noqa: Y015

@_typing.final
class CommandExecutionUUID(_message.Message):
    """-------- Framework Types --------"""

    DESCRIPTOR: _descriptor.Descriptor

    VALUE_FIELD_NUMBER: _builtins.int
    value: _builtins.str
    def __init__(
        self,
        *,
        value: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CommandExecutionUUID: _TypeAlias = CommandExecutionUUID  # noqa: Y015

@_typing.final
class CommandConfirmation(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    COMMANDEXECUTIONUUID_FIELD_NUMBER: _builtins.int
    LIFETIMEOFEXECUTION_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def commandExecutionUUID(self) -> Global___CommandExecutionUUID: ...
    @_builtins.property
    def lifetimeOfExecution(self) -> Global___Duration: ...
    def __init__(
        self,
        *,
        commandExecutionUUID: Global___CommandExecutionUUID | None = ...,
        lifetimeOfExecution: Global___Duration | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["commandExecutionUUID", b"commandExecutionUUID", "lifetimeOfExecution", b"lifetimeOfExecution"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["commandExecutionUUID", b"commandExecutionUUID", "lifetimeOfExecution", b"lifetimeOfExecution"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CommandConfirmation: _TypeAlias = CommandConfirmation  # noqa: Y015

@_typing.final
class ExecutionInfo(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _CommandStatus:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _CommandStatusEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[ExecutionInfo._CommandStatus.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        waiting: ExecutionInfo._CommandStatus.ValueType  # 0
        running: ExecutionInfo._CommandStatus.ValueType  # 1
        finishedSuccessfully: ExecutionInfo._CommandStatus.ValueType  # 2
        finishedWithError: ExecutionInfo._CommandStatus.ValueType  # 3

    class CommandStatus(_CommandStatus, metaclass=_CommandStatusEnumTypeWrapper): ...
    waiting: ExecutionInfo.CommandStatus.ValueType  # 0
    running: ExecutionInfo.CommandStatus.ValueType  # 1
    finishedSuccessfully: ExecutionInfo.CommandStatus.ValueType  # 2
    finishedWithError: ExecutionInfo.CommandStatus.ValueType  # 3

    COMMANDSTATUS_FIELD_NUMBER: _builtins.int
    PROGRESSINFO_FIELD_NUMBER: _builtins.int
    ESTIMATEDREMAININGTIME_FIELD_NUMBER: _builtins.int
    UPDATEDLIFETIMEOFEXECUTION_FIELD_NUMBER: _builtins.int
    commandStatus: Global___ExecutionInfo.CommandStatus.ValueType
    @_builtins.property
    def progressInfo(self) -> Global___Real: ...
    @_builtins.property
    def estimatedRemainingTime(self) -> Global___Duration: ...
    @_builtins.property
    def updatedLifetimeOfExecution(self) -> Global___Duration: ...
    def __init__(
        self,
        *,
        commandStatus: Global___ExecutionInfo.CommandStatus.ValueType = ...,
        progressInfo: Global___Real | None = ...,
        estimatedRemainingTime: Global___Duration | None = ...,
        updatedLifetimeOfExecution: Global___Duration | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["estimatedRemainingTime", b"estimatedRemainingTime", "progressInfo", b"progressInfo", "updatedLifetimeOfExecution", b"updatedLifetimeOfExecution"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["commandStatus", b"commandStatus", "estimatedRemainingTime", b"estimatedRemainingTime", "progressInfo", b"progressInfo", "updatedLifetimeOfExecution", b"updatedLifetimeOfExecution"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ExecutionInfo: _TypeAlias = ExecutionInfo  # noqa: Y015

@_typing.final
class SiLAError(_message.Message):
    """-------- Error Handling --------"""

    DESCRIPTOR: _descriptor.Descriptor

    VALIDATIONERROR_FIELD_NUMBER: _builtins.int
    DEFINEDEXECUTIONERROR_FIELD_NUMBER: _builtins.int
    UNDEFINEDEXECUTIONERROR_FIELD_NUMBER: _builtins.int
    FRAMEWORKERROR_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def validationError(self) -> Global___ValidationError: ...
    @_builtins.property
    def definedExecutionError(self) -> Global___DefinedExecutionError: ...
    @_builtins.property
    def undefinedExecutionError(self) -> Global___UndefinedExecutionError: ...
    @_builtins.property
    def frameworkError(self) -> Global___FrameworkError: ...
    def __init__(
        self,
        *,
        validationError: Global___ValidationError | None = ...,
        definedExecutionError: Global___DefinedExecutionError | None = ...,
        undefinedExecutionError: Global___UndefinedExecutionError | None = ...,
        frameworkError: Global___FrameworkError | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["definedExecutionError", b"definedExecutionError", "error", b"error", "frameworkError", b"frameworkError", "undefinedExecutionError", b"undefinedExecutionError", "validationError", b"validationError"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["definedExecutionError", b"definedExecutionError", "error", b"error", "frameworkError", b"frameworkError", "undefinedExecutionError", b"undefinedExecutionError", "validationError", b"validationError"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_error: _TypeAlias = _typing.Literal["validationError", "definedExecutionError", "undefinedExecutionError", "frameworkError"]  # noqa: Y015
    _WhichOneofArgType_error: _TypeAlias = _typing.Literal["error", b"error"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_error) -> _WhichOneofReturnType_error | None: ...

Global___SiLAError: _TypeAlias = SiLAError  # noqa: Y015

@_typing.final
class ValidationError(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PARAMETER_FIELD_NUMBER: _builtins.int
    MESSAGE_FIELD_NUMBER: _builtins.int
    parameter: _builtins.str
    """fully qualified parameter identifier"""
    message: _builtins.str
    def __init__(
        self,
        *,
        parameter: _builtins.str = ...,
        message: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["message", b"message", "parameter", b"parameter"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ValidationError: _TypeAlias = ValidationError  # noqa: Y015

@_typing.final
class DefinedExecutionError(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ERRORIDENTIFIER_FIELD_NUMBER: _builtins.int
    MESSAGE_FIELD_NUMBER: _builtins.int
    errorIdentifier: _builtins.str
    """fully qualified defined execution error identifier"""
    message: _builtins.str
    def __init__(
        self,
        *,
        errorIdentifier: _builtins.str = ...,
        message: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["errorIdentifier", b"errorIdentifier", "message", b"message"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DefinedExecutionError: _TypeAlias = DefinedExecutionError  # noqa: Y015

@_typing.final
class UndefinedExecutionError(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    MESSAGE_FIELD_NUMBER: _builtins.int
    message: _builtins.str
    def __init__(
        self,
        *,
        message: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["message", b"message"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___UndefinedExecutionError: _TypeAlias = UndefinedExecutionError  # noqa: Y015

@_typing.final
class FrameworkError(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _ErrorType:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _ErrorTypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[FrameworkError._ErrorType.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        COMMAND_EXECUTION_NOT_ACCEPTED: FrameworkError._ErrorType.ValueType  # 0
        INVALID_COMMAND_EXECUTION_UUID: FrameworkError._ErrorType.ValueType  # 1
        COMMAND_EXECUTION_NOT_FINISHED: FrameworkError._ErrorType.ValueType  # 2
        INVALID_METADATA: FrameworkError._ErrorType.ValueType  # 3
        NO_METADATA_ALLOWED: FrameworkError._ErrorType.ValueType  # 4

    class ErrorType(_ErrorType, metaclass=_ErrorTypeEnumTypeWrapper): ...
    COMMAND_EXECUTION_NOT_ACCEPTED: FrameworkError.ErrorType.ValueType  # 0
    INVALID_COMMAND_EXECUTION_UUID: FrameworkError.ErrorType.ValueType  # 1
    COMMAND_EXECUTION_NOT_FINISHED: FrameworkError.ErrorType.ValueType  # 2
    INVALID_METADATA: FrameworkError.ErrorType.ValueType  # 3
    NO_METADATA_ALLOWED: FrameworkError.ErrorType.ValueType  # 4

    ERRORTYPE_FIELD_NUMBER: _builtins.int
    MESSAGE_FIELD_NUMBER: _builtins.int
    errorType: Global___FrameworkError.ErrorType.ValueType
    message: _builtins.str
    def __init__(
        self,
        *,
        errorType: Global___FrameworkError.ErrorType.ValueType = ...,
        message: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["errorType", b"errorType", "message", b"message"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___FrameworkError: _TypeAlias = FrameworkError  # noqa: Y015

@_typing.final
class Timezone(_message.Message):
    """-------- Internal types --------
    Timezone: used in Date, Time, Timestamp
    """

    DESCRIPTOR: _descriptor.Descriptor

    HOURS_FIELD_NUMBER: _builtins.int
    MINUTES_FIELD_NUMBER: _builtins.int
    hours: _builtins.int
    minutes: _builtins.int
    def __init__(
        self,
        *,
        hours: _builtins.int = ...,
        minutes: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["hours", b"hours", "minutes", b"minutes"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Timezone: _TypeAlias = Timezone  # noqa: Y015

@_typing.final
class Duration(_message.Message):
    """Duration: used in CommandConfirmation, ExecutionInfo"""

    DESCRIPTOR: _descriptor.Descriptor

    SECONDS_FIELD_NUMBER: _builtins.int
    NANOS_FIELD_NUMBER: _builtins.int
    seconds: _builtins.int
    nanos: _builtins.int
    def __init__(
        self,
        *,
        seconds: _builtins.int = ...,
        nanos: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["nanos", b"nanos", "seconds", b"seconds"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Duration: _TypeAlias = Duration  # noqa: Y015
